export default {
    logo: require('../assets/images/logo.png.webp'),
    slide1: require('../assets/images/carousel1.jpg'),
    slide2: require('../assets/images/carousel2.jpg'),
    slide3: require('../assets/images/carousel3.webp'),
    img1: require('../assets/images/banner-02.jpg'),
    img2: require('../assets/images/banner-05.webp'),
    img3: require('../assets/images/item-05.jpg'),
    img4: require('../assets/images/banner-07.jpg'),
    img5: require('../assets/images/banner-04.jpg'),
    img6: require('../assets/images/banner-09.webp'),
    img7: require('../assets/images/item-03_700x933.webp'),
    img8: require('../assets/images/item-04_700x933.webp'),
    img9: require('../assets/images/item-10_700x933.webp'),
    img10: require('../assets/images/item-11_700x933.webp'),
    img11: require('../assets/images/item-12_700x933.webp'),
    img12: require('../assets/images/item-13_700x933.webp'),
    img13: require('../assets/images/item-15_700x933.webp'),
    img14: require('../assets/images/item-16_700x933.webp'),
    blog1: require('../assets/images/blog-01.jpg'),
    blog2: require('../assets/images/blog-02.jpg'),
    blog3: require('../assets/images/blog-03.jpg'),
}